[package]
name = "rebar"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "4.2.7"
color-eyre = "0.6.2"
env_logger = "0.10.0"
log = "0.4.17"
petgraph = "0.6.3"
serde = { version = "1.0.163", features = ["derive"] }
serde_yaml = "0.9.21"
tokio = { version = "1.28.1", features = ["macros", "rt-multi-thread"] }


# bio = "1.1.0"
# itertools = "0.10.5"
# csv = "1.2.1"
# tempfile = "3.5.0"
