[package]
name = "rebar"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bio = "1.1.0"
clap = { version = "4.2.7", features = ["derive"] }
color-eyre = "0.6.2"
env_logger = "0.10.0"
log = "0.4.17"
petgraph = "0.6.3"
serde = { version = "1.0.163", features = ["derive"] }
serde_yaml = "0.9.21"
tempfile = "3.5.0"
tokio = { version = "1.28.1", features = ["macros", "rt-multi-thread"] }
reqwest = "0.11.18"
url = "2.3.1"
zstd = "0.12.3+zstd.1.5.2"
