[package]
name = "rebar-utils"
version = "0.3.0"
edition = "2021"

[dependencies]
camino      = { version = "1.1.6",   default-features = false, features = ["serde1"] }
color-eyre = { version = "0.6.2",   default-features = false }
log        = { version = "0.4.17",  default-features = false }
