# Fully build the rebar application, for all supported arch and containers
name: Build

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
  release:
    types: [published]
  workflow_call:
    inputs:
      arch:
        required: true
        type: string
      os:
        required: true
        type: string
      binary:
        required: true
        type: string

jobs:

  # ---------------------------------------------------------------------------
  compile:
    uses: ./.github/workflows/compile.yaml
    strategy:
      fail-fast: false
      matrix:
        include:
          # Linux
          - arch: x86_64-unknown-linux-musl
            os: ubuntu-latest
            binary: rebar
          # Linux cross-compile to windows
          - arch: x86_64-pc-windows-gnu
            os: ubuntu-latest
            binary: rebar.exe
          # macOS
          - arch: x86_64-apple-darwin
            os: macos-latest
            binary: rebar
    with:
      arch: ${{ matrix.arch }}
      os: ${{ matrix.os }}
      binary: ${{ matrix.binary }}

  # ---------------------------------------------------------------------------
  docker:
    uses: ./.github/workflows/docker.yaml
