name: Build

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
  release:
    types: [published]
  workflow_call:

jobs:

  # ---------------------------------------------------------------------------
  build:

    strategy:
      fail-fast: false
      matrix:
        include:
          # Linux
          - os: ubuntu-latest
            arch: aarch64-unknown-linux-gnu
          - os: ubuntu-latest
            arch: aarch64-unknown-linux-musl
          - os: ubuntu-latest
            arch: x86_64-unknown-linux-gnu
          - os: ubuntu-latest
            arch: x86_64-unknown-linux-musl
          # Linux cross-compile to windows
          - os: ubuntu-latest
            arch: x86_64-pc-windows-gnu
          # MacOS
          - os: macos-latest
            arch: aarch64-apple-darwin
          - os: macos-latest
            arch: x86_64-apple-darwin

    runs-on: ${{ matrix.os }}

    steps:

      # ---------------------------------------------------------------------------
      # Linux Cross-Compile

      - name: checkout repo
        uses: actions/checkout@v3

      - name: setup rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.74.0

      - name: install cross
        run: |
          cargo install cross

      - name: build (linux cross-compile)
        if: matrix.os == 'ubuntu-latest'
        run: |
          cross build --release --all-features --target ${{ matrix.arch }}

      - name: build (macos)
        if: matrix.os == 'macos-latest'
        run: |
          cargo build --release --all-features --target ${{ matrix.arch }}

      - name: compress with upx
        uses: crazy-max/ghaction-upx@v3
        with:
          version: v4.1.0
          files: |
            target/${{ matrix.arch }}/release/rebar
          args: --best --lzma

      - name: upload binary
        uses: actions/upload-artifact@v3
        with:
          name: rebar-${{ matrix.arch }}
          path: target/${{ matrix.arch }}/release/rebar

      # ---------------------------------------------------------------------------
      # MacOS Compile
