name: Deploy to PyPI

on:
  release:

jobs:

  # Deploy package with twine
  deploy:
    runs-on: ubuntu-latest
    steps:

      - name: checkout repo
        uses: actions/checkout@v3

      - name: setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: pip install
        run: |
          pip install --upgrade pip
          pip install --upgrade setuptools wheel twine

      # - name: build and deploy
      #   env:
      #     TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
      #     TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      #   run: |
      #     python setup.py sdist bdist_wheel
      #     twine upload dist/*
      #     # twine upload --repository-url https://test.pypi.org/legacy/ dist/*
