name: Docker

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
  release:
    types: [published]
  workflow_call:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:

  build:
    uses: ./.github/workflows/build.yaml
    strategy:
      matrix:
        exclude:
          - arch: x86_64-pc-windows-gnu
            os: windows-latest
            binary: rebar.exe
          - arch: x86_64-apple-darwin
            os: macos-latest
            binary: rebar

  # ---------------------------------------------------------------------------
  docker:

    needs: build
    if: ${{ always() }}

    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:

      - name: checkout
        uses: actions/checkout@v3

      - name: download binary from build
        uses: actions/download-artifact@v3
        with:
          name: rebar-${{ matrix.arch }}
          path: target/${{ matrix.arch }}/release/

      - name: registry login
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: build
        uses: docker/build-push-action@v5
        with:
          context: .
          load: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: test
        run: |
          docker run --rm ${{ github.repository }}:$DOCKER_METADATA_OUTPUT_VERSION rebar --help
