name: Docker

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
  release:
    types: [published]
  workflow_call:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  IMAGE_TAG: ${{ github.repository }}:${{ github.ref_name }}

jobs:

  build:
    uses: ./.github/workflows/build.yaml
    strategy:
      matrix:
        arch: [x86_64-unknown-linux-musl]
        os: [ubuntu-latest]
        binary: [rebar]
    with:
      arch: ${{ matrix.arch }}
      os: ${{ matrix.os }}
      binary: ${{ matrix.binary }}

  # ---------------------------------------------------------------------------
  docker:

    needs: build

    strategy:
      fail-fast: false
      matrix:
        arch: [x86_64-unknown-linux-musl]
        os: [ubuntu-latest]
        binary: [rebar]

    runs-on: ${{ matrix.os }}

    permissions:
      contents: read
      packages: write

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: download binary from build
        uses: actions/download-artifact@v3
        with:
          name: rebar-${{ matrix.arch }}
          path: target/${{ matrix.arch }}/release/

      - name: update binary permission
        run: |
          chmod +x target/${{ matrix.arch }}/release/${{ matrix.binary }}

      - name: registry login
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: build local
        uses: docker/build-push-action@v5
        with:
          context: .
          tags: ${{ env.IMAGE_TAG }}
          outputs: type=docker,dest=rebar.tar

      - name: test local
        run: |
          docker load --input rebar.tar
          docker run ${{ env.IMAGE_TAG }} rebar --help

      # - name: build
      #   uses: docker/build-push-action@v5
      #   with:
      #     context: .
      #     load: true
      #     tags: ${{ steps.meta.outputs.tags }}
      #     labels: ${{ steps.meta.outputs.labels }}

      - name: upload image artifact
        uses: actions/upload-artifact@v3
        with:
          name: rebar-docker
          path: rebar.tar
          retention-days: 7
          if-no-files-found: error
