name: Latest

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
  release:
    types: [published]

  schedule:
  - cron: '0 0 * * *'

env:
  GITHUB_USERNAME: ${{ github.actor }}
  GITHUB_TOKEN: ${{ github.token }}

jobs:

  build:
    uses: ./.github/workflows/build.yaml

  # ---------------------------------------------------------------------------
  latest:

    needs: build

    strategy:
      fail-fast: false
      matrix:
        include:
          - arch: x86_64-unknown-linux-musl
            os: ubuntu-latest
            binary: rebar
          - arch: x86_64-pc-windows-gnu
            os: windows-latest
            binary: rebar.exe
          - arch: x86_64-apple-darwin
            os: macos-latest
            binary: rebar

    runs-on: ${{ matrix.os }}

    steps:
      - name: checkout repo
        uses: actions/checkout@v3

      - name: download binary from build
        uses: actions/download-artifact@v3
        with:
          name: rebar-${{ matrix.arch }}
          path: target/${{ matrix.arch }}/release

      - name: install
        run: |
          chmod +x target/${{ matrix.arch }}/release/${{ matrix.binary }}
          cp target/${{ matrix.arch }}/release/${{ matrix.binary }} .
          ./${{ matrix.binary }} --help

      - name: dataset download
        run: |
          ./${{ matrix.binary }} dataset download --name sars-cov-2 --tag latest --output-dir dataset/sars-cov-2/latest

      - name: validate
        run: |
          ./${{ matrix.binary }} run  --dataset-dir dataset/sars-cov-2/latest --output-dir validate --populations "*" --threads 2
          if [[ $(grep "fail" validate/linelist.tsv) ]]; then exit 1; fi

      - name: plot
        run: |
          ./${{ matrix.binary }} plot --dataset-dir dataset/sars-cov-2/latest --output-dir validate --plot-dir validate/plots

      - name: upload
        uses: actions/upload-artifact@v3
        with:
          name: validate-${{ matrix.arch }}
          path: validate
          if-no-files-found: error
          retention-days: 7
