name: Latest

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
  release:
    types: [published]

  schedule:
  - cron: '0 0 * * *'

env:
  tag: "latest"

jobs:

  build:
    uses: ./.github/workflows/build.yaml

  # ---------------------------------------------------------------------------
  latest:

    needs: build

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        arch:
          #- aarch64-apple-darwin
          #- aarch64-unknown-linux-gnu
          #- aarch64-unknown-linux-musl
          #- x86_64-apple-darwin
          #- x86_64-pc-windows-gnu
          - x86_64-unknown-linux-gnu
          #- x86_64-unknown-linux-musl

    steps:
      - name: checkout repo
        uses: actions/checkout@v3

      - name: download binary from build
        uses: actions/download-artifact@v3
        with:
          name: rebar-${{ matrix.arch }}
          path: target/${{ matrix.arch }}/release

      - name: install
        run: |
          mkdir -p /home/runner/.local/bin
          mv target/${{ matrix.arch }}/release/rebar ~/.local/bin
          chmod +x ~/.local/bin/rebar
          rebar --help

      - name: dataset download
        run: |
          rebar dataset download --name sars-cov-2 --tag $tag --output-dir dataset/sars-cov-2/$tag

      - name: validate
        run: |
          rebar run  --dataset-dir dataset/sars-cov-2/$tag --output-dir validate --populations "*" --threads 2
          if [[ $(grep "pass" output/validate/linelist.tsv) ]]; then exit 1; fi

      - name: plot
        run: |
          rebar plot --dataset-dir dataset/sars-cov-2/$tag --output-dir validate --plot-dir validate/plots

      - name: upload
        uses: actions/upload-artifact@v3
        with:
          name: validate-${{ matrix.arch }}
          path: validate
