name: Latest

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
  release:
    types: [published]

  schedule:
  - cron: '0 0 * * *'

env:
  GITHUB_USERNAME: ${{ github.actor }}
  GITHUB_TOKEN: ${{ github.token }}
  RUN_CMD: "./rebar"

jobs:

  # ---------------------------------------------------------------------------
  # Latest is a model/algorithm test, only needs the linux version compiled

  compile:
    uses: ./.github/workflows/compile.yaml
    strategy:
      fail-fast: false
      matrix:
        include:
          # Linux
          - arch: x86_64-unknown-linux-musl
            os: ubuntu-latest
            binary: rebar
    with:
      arch: ${{ matrix.arch }}
      os: ${{ matrix.os }}
      binary: ${{ matrix.binary }}

  # ---------------------------------------------------------------------------
  latest:

    needs: compile

    strategy:
      fail-fast: false
      matrix:
        include:
          # Linux
          - arch: x86_64-unknown-linux-musl
            os: ubuntu-latest
            binary: rebar

    runs-on: ${{ matrix.os }}

    steps:
      - name: checkout repo
        uses: actions/checkout@v3

      - name: download binary from build
        uses: actions/download-artifact@v3
        with:
          name: rebar-${{ matrix.arch }}
          path: target/${{ matrix.arch }}/release

      - name: install
        run: |
          chmod +x target/${{ matrix.arch }}/release/${{ matrix.binary }}
          cp target/${{ matrix.arch }}/release/${{ matrix.binary }} .
          ${{ env.RUN_CMD }} --help

      - name: dataset download
        run: |
          ${{ env.RUN_CMD }} dataset download --name sars-cov-2 --tag latest --output-dir dataset/sars-cov-2/latest

      - name: validate
        run: |
          ${{ env.RUN_CMD }} run  --dataset-dir dataset/sars-cov-2/latest --output-dir validate --populations "*" --threads 2
          if [[ $(grep "fail" validate/linelist.tsv) ]]; then exit 1; fi

      - name: plot
        run: |
          ${{ env.RUN_CMD }} plot --dataset-dir dataset/sars-cov-2/latest --output-dir validate --plot-dir validate/plots

      - name: upload
        uses: actions/upload-artifact@v3
        with:
          name: validate-${{ matrix.arch }}
          path: validate
          if-no-files-found: error
          retention-days: 7
