name: Lint

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
  release:
    types: [published]
  schedule:
    - cron: "0 0 * * *"

jobs:

  lint:

    runs-on: ubuntu-latest
    steps:

      - name: checkout repo
        uses: actions/checkout@v3

      - name: setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: setup linters
        run: |
          pip install pre-commit==2.17.0
          pre-commit install-hooks

      # lint all files
      - name: lint
        run: pre-commit run --all-files
