name: Pipeline

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
  release:
    types: [published]

jobs:

  pipeline:

    name: Pipeline
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:

      - name: checkout repo
        uses: actions/checkout@v3

      - name: setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: install package
        run: pip install .

      - name: run help
        run: rebar help

      - name: dataset
        run: rebar dataset --name sars-cov-2 --tag --outdir dataset/sars-cov-2-latest

      - name: run
        run: rebar run --dataset dataset/sars-cov-2-latest --output-all --lineages XA

      - name: validate
        run: rebar validate --dataset dataset/sars-cov-2-latest --output-tsv --outdir validate
