name: Release-Test

# on:
#   push:
#     tags:
#       - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
  release:
    types: [published]


jobs:

  build:
    uses: ./.github/workflows/build.yaml

  #----------------------------------------------------------------------------
  release:

    needs: build
    runs-on: ubuntu-latest

    steps:

      - name: download binaries from build
        uses: actions/download-artifact@v3
        with:
          path: target/release

      - name: check
        run: |
          ls -l target/release
          ls -l target/release/*

      # - name: create release
      #   uses: ncipollo/release-action@v1
      #   with:
      #     artifacts: target/x86_64-unknown-linux-gnu/release/rebar
      #     artifactErrorsFailBuild: true
      #     draft: true
      #     generateReleaseNotes: true
      #     makeLatest: true
      #     prerelease: true
