name: Release

on:
  push:
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:

  build:
    uses: ./.github/workflows/build.yaml

  #----------------------------------------------------------------------------
  release:

    needs: build
    runs-on: ubuntu-latest

    steps:

      - name: download build output
        uses: actions/download-artifact@v3
        with:
          path: target

      - name: rename binaries by architecture
        run: |
          mkdir target/release
          mv target/rebar-x86_64-unknown-linux-musl/rebar target/release/rebar-x86_64-unknown-linux-musl
          mv target/rebar-x86_64-unknown-linux-musl/rebar target/release/rebar-x86_64-unknown-linux-musl
          ls -l target/release/

      - name: create release
        uses: ncipollo/release-action@v1
        with:
          # comma-separated
          artifacts: "target/release/rebar-x86_64-unknown-linux-gnu,target/release/rebar-x86_64-unknown-linux-musl"
          # aarch64-apple-darwin
          # aarch64-unknown-linux-gnu
          # aarch64-unknown-linux-musl
          # x86_64-apple-darwin
          # x86_64-pc-windows-gnu

          artifactErrorsFailBuild: true
          draft: true
          generateReleaseNotes: true
          makeLatest: true
          prerelease: true
