name: Test

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
  release:
    types: [published]

jobs:

  build:

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        arch:
          #- aarch64-apple-darwin
          #- aarch64-unknown-linux-gnu
          #- aarch64-unknown-linux-musl
          #- x86_64-apple-darwin
          #- x86_64-pc-windows-gnu
          - x86_64-unknown-linux-gnu
          #- x86_64-unknown-linux-musl

    steps:
      - name: checkout repo
        uses: actions/checkout@v3

      - name: setup rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.69.0

      - name: build
        run: cargo build --release --all-features

      - name: dataset
        run: cargo run -- dataset download --output-dir dataset/sars-cov-2/latest --name sars-cov-2 --tag latest

      - name: run
        run: |
          cargo run -- run --dataset-dir dataset/sars-cov-2/latest --output-dir output/XBB.1.16 --populations "XBB.1.16,XBB.1.16.1"
