name: Test

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
  release:
    types: [published]

env:
  tag: "2023-11-17"

jobs:

  build:

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        arch:
          #- aarch64-apple-darwin
          #- aarch64-unknown-linux-gnu
          #- aarch64-unknown-linux-musl
          #- x86_64-apple-darwin
          #- x86_64-pc-windows-gnu
          - x86_64-unknown-linux-gnu
          #- x86_64-unknown-linux-musl

    steps:
      - name: checkout repo
        uses: actions/checkout@v3

      - name: setup rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.74.0

      - name: build
        run: |
          cargo build --release --all-features --target ${{ matrix.arch }}
          cp target/${{ matrix.arch }}/release/rebar .

      - name: compress with upx
        uses: crazy-max/ghaction-upx@v3
        with:
          version: v4.1.0
          files: |
            rebar
          args: --best --lzma

      - name: install
        run: |
          echo $PATH
          mv rebar /home/runner/.local/bin/rebar
          rebar --help

      - name: dataset list
        run: |
          rebar dataset list

      - name: dataset download
        run: |
          rebar dataset download --name sars-cov-2 --tag $tag --output-dir dataset/sars-cov-2/$tag

      - name: example 1
        run: |
          rebar run  --dataset-dir dataset/sars-cov-2/$tag --output-dir example1 --populations "AY.4.2*,BA.5.2,XBC.1.6*,XBB.1.5.1,XBL"
          rebar plot --dataset-dir dataset/sars-cov-2/$tag --output-dir example1 --plot-dir example1/plots

      - name: example 2
        run: |
          rebar run  --dataset-dir dataset/sars-cov-2/$tag --output-dir example2 --alignment data/example2.fasta
          rebar plot --dataset-dir dataset/sars-cov-2/$tag --output-dir example2 --plot-dir example2/plots
