name: Test

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
  release:
    types: [published]


jobs:
  # ---------------------------------------------------------------------------
  coverage:

    runs-on: ubuntu-latest
    env:
      CARGO_TERM_COLOR: always
    steps:

      - name: checkout repo
        uses: actions/checkout@v4

      - name: intall rust nightly
        run: rustup update nightly

      - name: install llvm-cov
        run: cargo +nightly install cargo-llvm-cov@0.6.4

      - name: generate code coverage
        run: cargo +nightly llvm-cov --doc --all-features --workspace --lcov --output-path lcov.info

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          files: lcov.info
          fail_ci_if_error: true

  # ---------------------------------------------------------------------------
  docs:

    runs-on: ubuntu-latest

    steps:
      - name: checkout repo
        uses: actions/checkout@v4

      - name: rebar-phylo docs
        run: cargo rustdoc --package rebar-phylo -- --html-in-header=assets/docs/header.html --html-after-content=assets/docs/after-content.html

      - name: rebar docs
        run: cargo rustdoc --package rebar -- --html-in-header=assets/docs/header.html --html-after-content=assets/docs/after-content.html

      - name: upload docs
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: docs
          path: |
            target/doc/rebar
            target/doc/rebar_phylo
          if-no-files-found: error
          retention-days: 7

  # ---------------------------------------------------------------------------
  unit:

    runs-on: ubuntu-latest

    steps:
      - name: checkout repo
        uses: actions/checkout@v4

      # todo!() might want to test --all-features and --no-default-features?
      - name: doc tests
        run: cargo test --doc --all-features
