name: Test

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
  release:
    types: [published]

jobs:

  pytest:

    name: Install
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.7, 3.8, 3.9, 3.10, 3.11]
    steps:

      - name: checkout repo
        uses: actions/checkout@v3

      - name: setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: install package
        run: pip install .[dev]

      # - name: pytest modules
      #   run: |
      #     python test/test.py

      # - name: codecov upload
      #   if: matrix.python-version == '3.9'
      #   uses: codecov/codecov-action@v1
      #   with:
      #     file: ./coverage.xml
      #     flags: unittests
      #     env_vars: OS,PYTHON
      #     name: codecov-umbrella
      #     fail_ci_if_error: true
