name: Test

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
  release:
    types: [published]


env:
  GITHUB_USERNAME: ${{ github.actor }}
  GITHUB_TOKEN: ${{ github.token }}

jobs:

  build:
    uses: ./.github/workflows/build.yaml

  # ---------------------------------------------------------------------------
  test:

    needs: build
    if: ${{ always() }}

    strategy:
      fail-fast: false
      matrix:
        include:
          - arch: x86_64-unknown-linux-musl
            os: ubuntu-latest
            binary: rebar
          - arch: x86_64-pc-windows-gnu
            os: windows-latest
            binary: rebar.exe
          - arch: x86_64-apple-darwin
            os: macos-latest
            binary: rebar

    runs-on: ${{ matrix.os }}

    steps:
      - name: checkout repo
        uses: actions/checkout@v3

      - name: download binary from build
        uses: actions/download-artifact@v3
        with:
          name: rebar-${{ matrix.arch }}
          path: target/${{ matrix.arch }}/release

      - name: install
        if:
        run: |
          chmod +x target/${{ matrix.arch }}/release/${{ matrix.binary }}
          cp target/${{ matrix.arch }}/release/${{ matrix.binary }} .
          ./${{ matrix.binary }} --help

      - name: dataset list
        run: |
          ./${{ matrix.binary }} dataset list

      - name: dataset download
        run: |
          ./${{ matrix.binary }} dataset download --name sars-cov-2 --tag 2023-11-17 --output-dir dataset/sars-cov-2/2023-11-17

      - name: example 1
        run: |
          ./${{ matrix.binary }} run  --dataset-dir dataset/sars-cov-2/2023-11-17 --output-dir output/example1 --populations "AY.4.2*,BA.5.2,XBC.1.6*,XBB.1.5.1,XBL"
          ./${{ matrix.binary }} plot --dataset-dir dataset/sars-cov-2/2023-11-17 --output-dir output/example1

      - name: example 2
        run: |
          ./${{ matrix.binary }} run  --dataset-dir dataset/sars-cov-2/2023-11-17 --output-dir output/example2 --alignment data/example2.fasta
          ./${{ matrix.binary }} plot --dataset-dir dataset/sars-cov-2/2023-11-17 --output-dir output/example2

      - name: toy1
        run: |
          ./${{ matrix.binary }} run  --dataset-dir dataset/toy1 --output-dir output/toy1 --populations "*" --mask 0,0 --min-length 1
          ./${{ matrix.binary }} plot --dataset-dir dataset/toy1 --output-dir output/toy1

      - name: upload output
        uses: actions/upload-artifact@v3
        with:
          name: output-${{ matrix.arch }}
          path: output
          if-no-files-found: error
          retention-days: 7
