name: Test

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
  release:
    types: [published]

jobs:

  build:

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        arch:
          #- aarch64-apple-darwin
          #- aarch64-unknown-linux-gnu
          #- aarch64-unknown-linux-musl
          #- x86_64-apple-darwin
          #- x86_64-pc-windows-gnu
          - x86_64-unknown-linux-gnu
          #- x86_64-unknown-linux-musl

    steps:
      - name: checkout repo
        uses: actions/checkout@v3

      - name: setup rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.69.0

      - name: build
        run: |
          cargo build --release --all-features --target ${{ matrix.arch }}
          cp target/${{ matrix.arch }}/release/rebar .

      - name: compress with upx
        uses: crazy-max/ghaction-upx@v3
        with:
          version: v4.1.0
          files: |
            rebar
          args: --best --lzma

      - name: example 1
        run: |
          ./rebar dataset download --name sars-cov-2 --tag 2023-09-21T12:00:00Z --output-dir dataset/sars-cov-2/2023-09-21T12:00:00Z
          ./rebar run  --dataset-dir dataset/sars-cov-2/2023-09-21T12:00:00Z --output-dir example1 --populations AY.4,BA.5.2,XD,XBB.1.5.1,XBL
          ./rebar plot --dataset-dir dataset/sars-cov-2/2023-09-21T12:00:00Z --output-dir example1 --plot-dir
