name: Validate

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
  release:
    types: [published]
  schedule:
    - cron: "0 0 * * *"

jobs:

  pipeline:

    name: Validate
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:

      - name: checkout repo
        uses: actions/checkout@v3

      - name: setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: install package
        run: pip install .

      - name: dataset
        run: rebar dataset --name sars-cov-2 --tag latest --outdir dataset/sars-cov-2-latest

      - name: validate
        run: rebar run --dataset dataset/sars-cov-2-latest --alignment dataset/sars-cov-2-latest/alignment.fasta --validate --threads 2 --output-all --outdir validate

      - name: upload
        uses: actions/upload-artifact@v2
        with:
          name: validate
          path: validate/
          retention-days: 30

      # Force a non-zero exit value if "false_positive" or "false_negative"
      # Force a non-zero exit value if "no_breakpoints", which applies
      # a positive recombinant that we couldn't find breakpoints for.
      - name: check
        run: |
          if [[ $(-E "false|no_breakpoints") ]]; then echo exit 1; fi
